// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using RepositoryUtil;
using System;
using System.Collections.Generic;

namespace AuthRepository.Models;

public partial class User
{
    public long Id { get; set; }

    public string Name { get; set; }

    public DateOnly Birthdate { get; set; }

    public string Document { get; set; }

    public string Password { get; set; }
}